esphome:
  name: esp-temp
  friendly_name: ESP_Temperature

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "u6/DlKymLHg39ief1if8ryBTc9ivTroeuaXteq2ujLA="



wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.87.13
    gateway: 192.168.87.1
    subnet: 255.255.255.0
ota:
  platform: esphome
captive_portal:
    