esphome:
  name: lidar
  friendly_name: lidar

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DRgm2Ji6xd7au/c/WMlq5aP3JASi85Oj+RzhfAJ+fjI="

ota:
  - platform: esphome
    password: "20d4e23351a716412522a29764f993ac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lidar Fallback Hotspot"
    password: "s2VuKYlc8z9M"

captive_portal:
    