substitutions:
  name: ratgdov25i-496086
  friendly_name: ratgdov2.5i 496086
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: t1y006joH8ehu3HfGcixWToJy1u6xxbklQLhZLfjMNg=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.87.25
    gateway: 192.168.87.1
    subnet: 255.255.255.0
ota:
  platform: esphome