substitutions:
  name: ratgdov25i-496086
  friendly_name: ratgdo
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25board_esp8266_d1_mini_lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: BmQu1JLg89JRbSwaIRt+PFZAWGEDpdrMH4Rqd2X9Jlk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
esp8266:
  board: d1_mini
